### PR TITLE
Add scripts for history maintenance

### PR DESCRIPTION
**Pull request by emcsween**
## Description

* bin/flush-history-queues sends queued history updates to the history system
* bin/force-history-resyncs forces a resync of any project that has a broken history

### CODE REVIEW

**Comment by mserranom** [comment]
Added a changelog entry. @das7pad would you mind giving an extra pair of eyes before merging?

**Review by mserranom — APPROVED** [review]

**Review by das7pad — APPROVED** [review]
LGTM. This will not work for very old versions of Server Pro, e.g. 2.7.1. Something to keep in mind when documenting it's use for the upgrade procedure.

**Comment by emcsween** [comment]
Given that the scripts will be included in the container in future releases, I don't plan to merge this PR anymore. Instead, I'll add the scripts to our regular release build. Is it ok if I close it, @mserranom ?

**Comment by mserranom** [comment]
> Given that the scripts will be included in the container in future releases, I don't plan to merge this PR anymore. Instead, I'll add the scripts to our regular release build. Is it ok if I close it, @mserranom ?

Yeah I think it's ok to close this, also taking into account @das7pad comments on incompatibilities with previous versions.

**Comment by emcsween** [comment]
Thanks. Closing.

**Pull request closed without merging**
