### PR TITLE
remove version in the docker compose file

### PR DESCRIPTION
**Pull request by Milokita**
## Description

remove version in the docker compose file

## Related issues / Pull Requests

latest docker would report, this PR address this warning
```
"WARN[0000] overleaf-toolkit/lib/docker-compose.base.yml: `version` is obsolete"
```

## Contributor Agreement

- [x] I confirm I have signed the [Contributor License Agreement](https://github.com/overleaf/overleaf/blob/master/CONTRIBUTING.md#contributor-license-agreement)

### CODE REVIEW

**Comment by ThexXTURBOXx** [comment]
This fix would still be much appreciated, I think. Is anyone able to approve and merge this?
This will also simplify the creation of a docker compose override slightly.

**Comment by das7pad** [comment]
Thanks for the suggestion @Milokita!

This is currently blocked as we still need to support docker-compose v1 in the Toolkit and removing the `version` field changes the behavior of docker-compose v1/breaks setups.

As noted in the [release notes for Server Pro 5.1](https://github.com/overleaf/overleaf/wiki/Release-Notes-5.x.x#deprecation-for-docker-compose-v1), we are planning to drop support for docker-compose v1 with the next release. At this point we can adopt this PR.

**Comment by ltalirz** [comment]
Server Pro 5.2 is released, so I believe this PR could now go ahead

**Comment by ThexXTURBOXx** [comment]
@ltalirz This PR is not needed anymore because the `version` tags were already removed in c0767eec41b1befdda56b4d19164f47c5a398ad5

**Comment by das7pad** [comment]
We've made the changes to all the docker-compose files as part of the release in https://github.com/overleaf/toolkit/pull/299.
Thanks again for your contribution @Milokita !

**Pull request closed without merging**
