### PR TITLE
Revert "Release Server Pro 5.0.2"

### PR DESCRIPTION
**Pull request by mserranom**
Reverts overleaf/toolkit#241

### CODE REVIEW

**Review by das7pad — COMMENTED** [review]
We need to revert the retraction notice as well

**Comment by das7pad** [comment]
(as there is no follow up release available.)

**Comment by mserranom** [comment]
> We need to revert the retraction notice as well

Done in https://github.com/overleaf/toolkit/pull/244

**Review by das7pad — APPROVED** [review]

**Comment by das7pad** [comment]
Thanks!

**Pull request merged**
