### PR TITLE
Migrate to Compose v2

### LINKED ISSUE #119: Support for `docker compose` instead of `docker-compose`
This should be a really simple fix, by maybe adding a try catch logic at `bin/docker-compose`.

### PR DESCRIPTION
**Pull request by Colonel-Rogue**
## Description
- Updated references to `docker-compose` command to `docker compose`
- Moved `bin/docker-compose` → `bin/compose` to align with Compose's new terminology (they call it compose, not docker compose) and updated references to this file
- Updated references to `docker-compose` project to `compose`

## Related issues / Pull Requests
- fixes #119 

## Contributor Agreement

- [✅] I confirm I have signed the [Contributor License Agreement](https://github.com/overleaf/overleaf/blob/master/CONTRIBUTING.md#contributor-license-agreement)

### CODE REVIEW

**Comment by Geezus42** [comment]
Literally running into this right now. 😄

**Review by Geezus42 — APPROVED** [review]
Looks like a pretty straight forward find and replace.

**Comment by TimJ0212** [comment]
Thank you for your fix. If I'm running it on Ubuntu Server, I get an error: 
`bin/up: line 41: /root/overleaf-toolkit/bin/compose: Permission denied`
Would you have an idea what could be the reason ? I'm new to docker...

**Comment by Colonel-Rogue** [comment]
> Thank you for your fix. If I'm running it on Ubuntu Server, I get an error: `bin/up: line 41: /root/overleaf-toolkit/bin/compose: Permission denied` Would you have an idea what could be the reason ? I'm new to docker...

So you cloned your overleaf toolkit into `/root` (which is the superadmin's home directory) I'm assuming you're not logged in as root, otherwise you wouldn't have that issue. Go ahead and run `cd` after you login, and clone/run overleaf from there.

**Comment by TimJ0212** [comment]
I don't know why, but the bin/compose file had missing right for execution. Now everything works fine. Thank you for your work.

**Comment by Geezus42** [comment]
I ran into that too, just thought I missed something. Had to chmod /bin/compose to add execution permission.

**Comment by JuneKelly** [comment]
Hi! Thanks for opening this PR. We're going to take some time to consider how to integrate this change while maintaining backward compatibility for various existing installations. We'll update this PR when we have a decision. 

Thanks again!

**Comment by mserranom** [comment]
@Geezus42 we have this change in our roadmap, but as @JuneKelly pointed, this PR as it is forces admins to upgrade docker and docker-compose to get to v2. We need to make some changes to support both v1 and v2 (likely a change in the `bin/docker-compose` wrapper to detect which implementation is available, and a `bin/compose` counterpart, so admins don't have their automation broken). 

It's also worth noting that according to https://docs.docker.com/compose/compose-v2/, it's possible for user-admins to install compose v2 in such a way as to be available both as `docker compose` and `docker-compose`. This is also a potential temporary workaround.

> We’ve now marked Compose V1 as deprecated. Only high-priority security patches and critical bug fixes will apply to V1 until the next milestone.

Just to clarify: being deprecated doesn't mean Compose V1 is EOL.

**Comment by Colonel-Rogue** [comment]
Shouldn't this be released with a major version bump then? 
Edit: toolkit doesn't appear to have semantic versioning now, but it should - case in point.

**Comment by mserranom** [comment]
>  toolkit doesn't appear to have semantic versioning now, but it should

The toolkit doesn't have versioning. The supported version of the toolkit is the latest revision, which should be backwards compatible with different versions of Overleaf CE and Server Pro. Toolkit users should keep their checkout of this repo updated.

**Comment by Colonel-Rogue** [comment]
Closing this as maintainers want to go a different direction with their update plan, my fork will remain available but will not receive updates from upstream. Thanks all.

**Comment by emcsween** [comment]
We've done a backwards compatible version of this PR in #158. Thanks for initiating this work.

**Pull request closed without merging**
